version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper-custom
    ports:
      - "32181:2181"  # Host:Container
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka-custom
    ports:
      - "29092:29092"  # Host:Container
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-custom:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
